### ISSUE TITLE
UI: Course URL Copied success message inconsistent

### ISSUE THREAD

**Issue by qurat08** [ude-soco/CourseMapper-webserver#1105]
When clicking on share course option, course URL is copied and a success message is shown in green color.
The rest of the success messages in whole system are in blue color.
This is incosistency.

The success message in green should be changed to blue like other ones.
Current:
![image](https://github.com/user-attachments/assets/769d8631-d088-4d34-80a7-44404c74456f)

expected:
![image](https://github.com/user-attachments/assets/25cfcd1f-490d-4ec1-a8be-2af514c81628)

suggestion: The default success message in blue has an i icon, the green one has a tick mark. Tick mark on all the success messages throughout would look better, however this is an optional change.

**Comment by rawaa123** [comment]
i will change it to blue msg for new and later we can make it green the whole system

**Comment by qurat08** [comment]
please test it with delete topic and delete channel.. it appears in grey
![image](https://github.com/user-attachments/assets/03212acd-7f22-454c-9031-a93955f30ec1)

**Comment by qurat08** [comment]
fixed
