### ISSUE TITLE
Unable to upload PDF material, retrieve and delete it

### ISSUE THREAD

**Issue by qurat08** [ude-soco/CourseMapper-webserver#1119]
In the xapi feature branch ([ude-soco/CourseMapper-webserver at feature/1023-update-xapi-collection-statements (github.com)](https://github.com/ude-soco/CourseMapper-webserver/tree/feature/1023-update-xapi-collection-statements)).

⁠I am unable to upload a PDF material, it shows this error, however after uploading I can see the material tab created with the material name but PDF doesnt render on the UI.

when I upload the material I see this:
![image](https://github.com/user-attachments/assets/a55f5b06-5ff9-443b-8b82-d46fb4e6d6ac)

clicking on ok:
![image](https://github.com/user-attachments/assets/52973e5f-4325-4431-b87f-a110cd36ceff)

but I see the materials tab anyway, clicking on a tab: unable to see the material
![image](https://github.com/user-attachments/assets/3a058a1e-3b30-413e-ae73-cc643914c23f)

however I can see the entries in mongodb, 
![image](https://github.com/user-attachments/assets/ee41e99b-aa6b-4735-86dd-a012f4e92d8c)

But trying to delete the material from UI, crashes the server.

here is the console when I try to access a material:
![image](https://github.com/user-attachments/assets/51159725-e6ac-44a8-bce3-1ddc26e63c47)

**Comment by shoebjoarder** [comment]
Error is not reproducible. 
Moreover, the screenshots don't seem correct. The uploaded material was named in the UI screenshot is "one material". However, the database entry shows "LA material with long name".

**Comment by qurat08** [comment]
I tried uploading many PDF materials and LA material was one of them. here is the screenshot with the required material name
![image](https://github.com/user-attachments/assets/5d61043c-c9f9-4abf-b373-51fa764c0dcc)

**Comment by qurat08** [comment]
I still am not able to upload a pdf material
![image](https://github.com/user-attachments/assets/3451bca7-d454-41c0-8558-ff1aa62155e6)

**Comment by qurat08** [comment]
the issue is fixed if we have pdfs folder in src and it contain gitignore file with *

**Comment by shoebjoarder** [comment]
It has been fixed in the main branch now [70158a9](https://github.com/ude-soco/CourseMapper-webserver/commit/70158a9c0d0924f4a0149fb49aac9a0415f28553).
