### ISSUE TITLE
Issue with 'mention' notifications

### ISSUE THREAD

**Issue by qurat08** [ude-soco/CourseMapper-webserver#1122]
When I mention someone, the notification text contain a few alphabets from the annotation text whici I thing is a mistake, as it does not communicate anything.
How is it in feature branch:
![image](https://github.com/user-attachments/assets/0634c384-3175-4eee-880f-14f65bb934dc)
the text of this annotation is: now mention @new users

How it should be, as on edge:
![image](https://github.com/user-attachments/assets/fcda4da3-78d8-4df9-920e-57b2c6c4a4f7)
(Please check if there are 2 spaces in the area that I marked red, if yes, please remove one space.)

**Comment by shoebjoarder** [comment]
@qurat08 

Earlier, when someone mentioned some else, this was shown:

![image](https://github.com/user-attachments/assets/23a96a93-c484-4e87-b6a0-8b1debc6d318)


What do you think of adding a small preview of the annotation?

![image](https://github.com/user-attachments/assets/1451029e-f740-4803-b20e-c765ed2c09ca)

**Comment by qurat08** [comment]
thats a good idea

**Comment by qurat08** [comment]
may be enclose the annotation in "" to differentiate it from rest of the test
