### ISSUE TITLE
UI: Deleting a concept opens right click panel

### ISSUE THREAD

**Issue by qurat08** [ude-soco/CourseMapper-webserver#1129]
When I right click on a concept in material Kg preview to delete it, the right click panel of the browser opens as well. it should just open the delete popup.
![image](https://github.com/user-attachments/assets/c1273732-189a-475b-b67a-db7a8db84c22)

**Comment by jeanqussa** [comment]
I could not replicate this issue in Firefox or Chrome.

**Comment by qurat08** [comment]
I faced this in edge. But surprisingly only for this particular right click action on kg nodes while editing them. When i do the same action with MC nodes in slide kg to mark them u or dnu, this does not happen in the same browser.

**Comment by qurat08** [comment]
I could also reproduce this in chrome
![image](https://github.com/user-attachments/assets/588194fc-b8fe-4879-ab63-6911616a8856)

**Comment by qurat08** [comment]
@ahmedmohyh can you please try to reproduce it? if yes, can you may be fix this issue?

**Comment by qurat08** [comment]
Does not exist anymore because delete is changed to bulk deletion.
