### ISSUE TITLE
Mention someone is not shown in blue like before

### ISSUE THREAD

**Issue by qurat08** [ude-soco/CourseMapper-webserver#1132]
When you mention someone using @ it appears with @ and the name in normal font
It used to be in blue, without @ previously. 
How it is now:
![image](https://github.com/user-attachments/assets/81776caf-3210-40d4-8adf-b335fcab5a9e)

Expected:
![image](https://github.com/user-attachments/assets/bdd83754-6d39-4d23-8e4e-41566f861e2d)

**Comment by qurat08** [comment]
the same is happening with hashtags.. they also do not appear in blue in the annotations

**Comment by rawaa123** [comment]
things have fixed:
1. if the URL/hashtag ends on the truncation point
2. both are in Blue

**Comment by qurat08** [comment]
fixed
