### ISSUE TITLE
not able to see the recommendation button

### ISSUE THREAD

**Issue by rawaa123** [ude-soco/CourseMapper-webserver#1339]
not able to see the recommendation button, even when scrolling to the end of the page
![image](https://github.com/user-attachments/assets/a215a6fc-3ed0-44f5-b46a-468d4ca2f855)
i had to zoom in to get the recommendation button
![image](https://github.com/user-attachments/assets/ab7ed51d-709d-47c0-9fb6-991b655fa5ec)

**Comment by Boby024** [comment]
solved
