### ISSUE TITLE
Issues with #hashtags functionality

### ISSUE THREAD

**Issue by qurat08** [ude-soco/CourseMapper-webserver#858]
1) in the same slide set, if I have two annotations with #consistency, for example, it only shows the first annotation. Course: AWT, Channel Express Lecture, Material: Express - Draft 1
![Screenshot from 2024-05-07 12-47-58](https://github.com/ude-soco/CourseMapper-webserver/assets/23054665/ba603263-c6f3-47f8-8d93-860e2eeb257d)

2)When I added a new hashtag, #consistent, it showed up at the bottom for me (but in real-time from the professor's side, he doesn't see the update in his browser). Later, if I change the hashtag to #consistency, the #consistent hashtag doesn't get removed at the bottom. Furthermore, if I click on that #consistent from below, it shows the annotations of #consistency. Moreover, it only shows two annotations, where I added three annotations with #consistency.
![Screenshot from 2024-05-07 12-54-44](https://github.com/ude-soco/CourseMapper-webserver/assets/23054665/a5becfbe-bb01-4982-91d5-90821f52ce3f)

3) Certain hashtags are not recognized and n
![Bild (1)](https://github.com/ude-soco/CourseMapper-webserver/assets/23054665/98de3acc-7b53-48b1-96b0-944990230c44)
ot added to the left bottom panel

**Comment by ahmedmohyh** [comment]
4) for the certain tags that are not recognized, that's happen only when we create tags in new lines, i.e when the enter button is entered and then this tag is not recognized for some reason

**Comment by qurat08** [comment]
the issue is still there. 
1) The hashtag does not appear in blue in the annotation, it should appear in blue and clickable. when you clik on it, it takes you to the page with annotations mentioning that hashtag
![image](https://github.com/user-attachments/assets/cc3d13ab-8b57-44e5-9099-24c89c5b7e0e)
2) Not all annotations with a certain hashtag are retrieved when i click on a hashtag. For example, I added 2 annotations with #hashtag and another user added 2 annotations with #hashtag on the same material. when I click on #hashtag in the left panel, I see only two annotations added by me

this is what I have:
![image](https://github.com/user-attachments/assets/1900e572-2bde-4177-889b-5eaf0ae4e125)

this is what I see when clicking on #hashtags 
![image](https://github.com/user-attachments/assets/5122cd74-166f-4a2d-bba6-b9200687be03)

**Comment by qurat08** [comment]
@ahmedmohyh  
the tags are recognized and appear in blue. 
clicking on a tag retrieves all the annotations mentioning that tag, however, Please check this scenario: when an annotation contains the same tag twice, it appears two times in tags page: 
![image](https://github.com/user-attachments/assets/79b13820-614c-46b1-813d-0542a0306ce6)

**Comment by ahmedmohyh** [comment]
> @ahmedmohyh the tags are recognized and appear in blue. clicking on a tag retrieves all the annotations mentioning that tag, however, Please check this scenario: when an annotation contains the same tag twice, it appears two times in tags page: ![image](https://private-user-images.githubusercontent.com/23054665/375451395-79b13820-614c-46b1-813d-0542a0306ce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1OTgyNDMsIm5iZiI6MTcyODU5Nzk0MywicGF0aCI6Ii8yMzA1NDY2NS8zNzU0NTEzOTUtNzliMTM4MjAtNjE0Yy00NmIxLTgxM2QtMDU0MmEwMzA2Y2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDIyMDU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZGQ1MWQ1MGFjMGQ1NjZhMGYyNDczM2Y3ZWVhMTlkNmQ4OGQ2YTE2N2M3NTAxYWJhOGY5OGZjMzM3MmUyMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UbMNGUOQilndJlAN3FGH24nQfhT07fCUx2jZFo6AV1Y)

this problem should be solved and can be tested on edge as well

**Comment by qurat08** [comment]
fixed
